TUMBLR_OAUTH_KEY: 'cun2jUIyCOafiViY12UWq5G2lK4UnzZVmA2ymebiwLLvWOjRKf'
TUMBLR_OAUTH_SECRET: 'X3O7i4QKT3iZT4cMNROlVTWq0qSrhbpHqZSBPKRa8DQcN8Abka'
TUMBLR_API_TOKEN: 'xHJIFgLEhv0fpJdhLaF46zyrdMiNtVxIGEsrSbvULFTmFpEnMg'
TUMBLR_API_TOKEN_SECRET: 'aBQOT0zLcuYX7BzH46HOU9i6jQIJCIk8BxTHc7mbFWcXzk9bvc'
TUMBLR_BLOG: 'cottcodetestblog.tumblr.com'
